# Generated by Django 2.2 on 2022-10-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpdataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.IntegerField()),
                ('empname', models.CharField(max_length=100)),
                ('empsal', models.FloatField()),
                ('empaddress', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Empdata',
            },
        ),
    ]
